


abbreviations_to_full_names = {
    'JPMAM': 'J.P. Morgan Asset Management',
    'Barclays': 'Barclays PLC',
    'PFZW': 'Pensioenfonds Zorg en Welzijn',
    'Novartis': 'Novartis International AG',
    'EU': 'European Union',
    'MSCI': 'MSCI Inc.',
    'Exxon': 'Exxon Mobil Corporation',
    'BlackRock': 'BlackRock, Inc.',
    'Impact': 'Impact Coatings AB',  
    'Bloomberg': 'Bloomberg L.P.',
    'Cazenove': 'J.P. Morgan Cazenove',  
    'Fidelity': 'Fidelity Investments',
    'Aviva': 'Aviva plc',
    'Novelis': 'Novelis Inc.',
    'UK': 'United Kingdom',
    'UBS': 'UBS Group AG',
    'Amazon': 'Amazon.com, Inc.',
    'MetLife': 'MetLife, Inc.',
    'UBP': 'Union Bancaire Privée UBP SA',
    'Carlyle': 'The Carlyle Group Inc.',  
    'PMI': 'Philip Morris International Inc.',
    'Credit': 'Credit Suisse Group AG', 
    'AP7': 'Sjunde AP-fonden',
    'Endeavour': 'Endeavour Silver Corp.',
    'Robeco': 'Robeco',
    'Citi': 'Citigroup Inc.',
    'OMV': 'OMV Aktiengesellschaft',
    'HM': 'H&M Hennes & Mauritz AB',
    'Shell': 'Royal Dutch Shell plc',
    'WFE': 'World Federation of Exchanges',
    'Nestlé': 'Nestlé S.A.',
    'Jefferies': 'Jefferies Financial Group Inc.',
    'Smurfit': 'Smurfit Kappa Group plc',
    'BMO': 'Bank of Montreal',
    'AXA': 'AXA S.A.',
    'CSAM': 'China Asset Management Co., Ltd.',
    'S&P': 'Standard & Poor\'s Financial Services LLC',
    'EU': 'European Union',
    'Piper': 'Piper Sandler Companies',
    'LSEG': 'London Stock Exchange Group plc',
    'DB': 'Deutsche Bank AG',
    'Germany': 'Federal Republic of Germany',
    'HSBC': 'HSBC Holdings plc',
    'Barclays': 'Barclays PLC',
    'Santander': 'Banco Santander, S.A.',
    'Houlihan': 'Houlihan Lokey, Inc.',
    'Northern': 'Northern Trust Corporation',
    'Pioneer': 'Pioneer Natural Resources Company',
    'Lundin': 'Lundin Mining Corporation',
    'Atmos': 'Atmos Energy Corporation',
    'RMR': 'The RMR Group Inc.',
    'Blackstone': 'The Blackstone Group Inc.',
    'Fidelity': 'Fidelity Investments',
    'Farfetch': 'Farfetch Limited',
    'EU': 'European Union',
    'KKR': 'Kohlberg Kravis Roberts & Co. L.P.',
    'Banks': 'Banks.com, Inc.',
    'Aramco': 'Saudi Arabian Oil Company (Saudi Aramco)',
    'UBP': 'Union Bancaire Privée UBP SA',
    'BNP': 'BNP Paribas S.A.',
    'AIG': 'American International Group, Inc.',
    'Schroders': 'Schroders plc',
    'Jefferies': 'Jefferies Financial Group Inc.',
    'Newmont': 'Newmont Corporation',
    'BofA': 'Bank of America Corporation',
    'European': 'European Commission (or European Union)',
    'DuPont': 'DuPont de Nemours, Inc.',
    'Franklin': 'Franklin Resources, Inc.',
    'Robeco': 'Robeco',
    'Citi': 'Citigroup Inc.',
    'Martin': 'Martin Marietta Materials, Inc.',
    'UN': 'United Nations',
    'HSBC': 'HSBC Holdings plc',
    'SEC': 'U.S. Securities and Exchange Commission',
    'Equinor': 'Equinor ASA',
    'UBS': 'UBS Group AG',
    'Ericsson': 'Telefonaktiebolaget LM Ericsson (Ericsson)',
    'FRC': 'Financial Reporting Council (UK)',
    'AIG': 'American International Group, Inc.',
    'AllianzGI': 'Allianz Global Investors',
    'Trafigura': 'Trafigura Group Pte. Ltd.',
    'Aviva': 'Aviva plc',
    'NYSTRS': 'New York State Teachers\' Retirement System',
    'CaixaBank': 'CaixaBank, S.A.',
    'ExxonMobil': 'Exxon Mobil Corporation',
    'HSBC': 'HSBC Holdings plc',
    'Zero100': 'Not identified (please provide additional context)',
    'J.': 'J.C. Penney Company, Inc. (if referring to "J. C. Penney")',
    'Nest': 'Nestlé S.A.',
    'FCA': 'Fiat Chrysler Automobiles N.V.',
    'BNY': 'The Bank of New York Mellon Corporation (BNY Mellon)',
    'ESG': 'Environmental, Social, and Governance',
    'Coutts': 'Coutts & Co. (private bank)',
    'VTB': 'VTB Bank (Public Joint-Stock Company)',
    'ESG': 'Environmental, Social, and Governance',
    'Maersk': 'A.P. Møller - Mærsk A/S (Maersk Group)',
    'COP26': 'Conference of the Parties 26 (UN Climate Change Conference)',
    'MS': 'Morgan Stanley',
    'ISS': 'Institutional Shareholder Services Inc.',
    'Few': 'Fewer & Partners (a law firm)',
    'ING': 'ING Group N.V.',
    'Dow': 'The Dow Chemical Company',
    'FCA': 'Fiat Chrysler Automobiles N.V.',
    'LGIM': 'Legal & General Investment Management Limited',
    'ING': 'ING Group N.V.',
    'Shell': 'Royal Dutch Shell plc',
    'SPACs': 'Special Purpose Acquisition Companies',
    'Deutsche': 'Deutsche Bank AG',
    'BritainÃ¢Â€Â™s': 'United Kingdom',
    'JPM': 'JPMorgan Chase & Co.',
    'ESG': 'Environmental, Social, and Governance',
    'UBS': 'UBS Group AG',
    'Eurasian': 'Eurasian Natural Resources Corporation',
    'Natixis': 'Natixis S.A.',
    'Only': 'OnlyFans',
    'BHP': 'BHP Group',
    'Citi': 'Citigroup Inc.',
    'Sustainable': 'Sustainable Development',
    'BofA': 'Bank of America Corporation',
    'Fitch': 'Fitch Ratings Inc.',
    'MSCI': 'MSCI Inc.',
    'VÃƒÂ¤rde': 'Värde Partners',
    'Study': 'Study Group',
    'BNP': 'BNP Paribas S.A.',
    'Cowen': 'Cowen Inc.',
    'SEC': 'U.S. Securities and Exchange Commission',
    'Toyota': 'Toyota Motor Corporation',
    'Aviva': 'Aviva plc',
    'Amundi': 'Amundi',
    'SMI': 'Swiss Market Index',
    'GS': 'Goldman Sachs Group, Inc.',
    'VW': 'Volkswagen AG',
    'MSIM': 'Morgan Stanley Investment Management',
    'Rathbone': 'Rathbone Brothers Plc',
    'Fidelity': 'Fidelity Investments',
    'Robeco': 'Robeco',
    'Engie': 'Engie',
    'Diageo': 'Diageo plc',
    'Goldman': 'Goldman Sachs Group, Inc.',
    'UK': 'United Kingdom',
    'PCAF': 'Partnership for Carbon Accounting Financials',
    'Top': 'Topshop',
    'S&P': 'Standard & Poor\'s Financial Services LLC',
    'DWS': 'DWS Group GmbH & Co. KGaA',
    'TD': 'Toronto-Dominion Bank',
    'Blackstone': 'The Blackstone Group Inc.',
    'Janus': 'Janus Henderson Group plc',
    'HKSFC': 'Hong Kong Securities and Futures Commission',
    'Neuberger': 'Neuberger Berman Group LLC',
    'Brunel': 'Brunel University London',
    'Cazenove': 'J.P. Morgan Cazenove',
    'Barclays': 'Barclays PLC',
    'Refinitiv': 'Refinitiv',
    'Credit': 'Credit Suisse Group AG',
    'Nordea': 'Nordea Bank Abp',
    'Polar': 'Polar Capital Holdings plc',
    'Anti-corruption': 'Anti-corruption',
    'EC': 'European Commission',
    'Allianz': 'Allianz SE',
    'Mirabaud': 'Mirabaud Group',
    'MUFG': 'Mitsubishi UFJ Financial Group, Inc.',
    'ILN': 'International Lawyers Network',
    'Five': 'Five Below, Inc.',
    'Patrizia': 'Patrizia AG',
    'Big': 'Big Lots, Inc.',
    'SC': 'Santander Consumer USA Holdings Inc.',
    'CA100+': 'CA100+ Annual Investment Forum',
    'Ikea': 'IKEA',
    'Mark': 'Markel Corporation',
    'Cazenove': 'J.P. Morgan Cazenove',
    'ANZ': 'Australia and New Zealand Banking Group Limited (ANZ)',
    'CaixaBank': 'CaixaBank, S.A.',
    'Barclays': 'Barclays PLC',
    'Alphabet': 'Alphabet Inc.',
    'HSBC': 'HSBC Holdings plc',
    'Deutsche': 'Deutsche Bank AG',
    'MS': 'Morgan Stanley',
    'Climate': 'Climate Change',
    'Octopus': 'Octopus Energy Group Limited',
    'SEC': 'U.S. Securities and Exchange Commission',
    'Philip': 'Philip Morris International Inc.',
    'VolkerFitzpatrick': 'VolkerFitzpatrick',
    'Large': 'Large Scale Investments',
    'UBS': 'UBS Group AG',
    'BHP': 'BHP Group',
    'Norges': 'Norges Bank Investment Management',
    'T.': 'T. Rowe Price Group, Inc.',
    'Smurfit': 'Smurfit Kappa Group plc',
    'Total': 'TotalEnergies SE',
    'Asia': 'Asia',
    'Prada': 'Prada S.p.A.',
    'Microsoft': 'Microsoft Corporation',
    'BP': 'BP p.l.c.',
    'BMO': 'Bank of Montreal (BMO Financial Group)',
    'STOXX': 'STOXX Ltd.',
    'PepsiCo': 'PepsiCo, Inc.',
    'QSE': 'Qatar Stock Exchange',
    'Unilever,': 'Unilever PLC',
    'McDonald’s:': 'McDonalds Corporation'
}