

environment_keywords = ['climate', 'environment', 'green', 'sustainable', 'sustainability', 'carbon', 'renewable', 'ecosystem', 'conservation', 'carbon-neutral',"sustainability report",
    "carbon trading",
    "emissions",
    "climate change",
    "carbon neutral",
    "carbon dioxide",
    "greenhouse gas",
    "climate goals",
    "net zero",
    "renewable energy",
    "environmental stewardship",
    "ocean-going container vessels",
    "green bond",
    "ESG Report",
    "emissions reduction",
    "net-zero carbon emissions",
    "greenhouse gas emissions",
    "cement industry",
    "net zero greenhouse gas emissions",
    "emissions trading system",
    "Emissions Trading System",
    "sustainability bonds",
    "climate-related disclosure",
    "Paris Agreement",
    "ESG strategies",
    "global temperature rise",
    "ESG team",
    "environmental business initiative",
    "utilities",
    "diversity",
    "climate scenario analysis",
    "sustainability solutions",
    "sustainability financing",
    "sustainability bonds",
    "sustainability targets",
    "carbon neutral",
    "sustainability initiatives",
    "sustainable finance",
    "climate finance",
    "sustainability practices","oil","coal","gas","fuel","Sustainability report",
    "ESG ratings",
    "Stakeholder Capitalism Metrics",
    "Renewable electricity",
    "Climate-related financial disclosures",
    "ESG targets",
    "Sustainable Fixed Income Opportunities Fund",
    "Finance for Biodiversity Pledge",
    "Sustainability website",
    "Task Force on Climate-related Financial Disclosures",
    "ESG business",
    "Sustainability reporting",
    "Net-zero greenhouse gas emissions",
    "ESG reporting obligations",
    "Green hybrid bonds",
    "Society 2030: Spirit of Progress",
    "ESG inflows",
    "Green industrial revolution",
    "Global GHG Accounting and Reporting Standard",
    "Sustainability Accounting Standards Board",
    "Dow Jones Sustainability Indices",
    "ESG Advisory Board",
    "Climate risk disclosure rules",
    "Net-zero greenhouse gas emissions target",
    "Real Estate ESG",
    "ESG investments",
    "Climate-related risks disclosure",
    "Climate change mitigation",
    "ESG Leadership",
    "Climate Action 100+",
    "Sustainable solutions",
    "New EU ESG disclosure rules",
    "ESG and impact fund investing",
    "ESG Investing Olympics",
    "Sustainable Development Goals",
    "Carbon emissions offset",
    "ESG teams",
    "Sustainability bonds",
    "ESG solutions unit",
    "Fossil fuels policy",
    "Partnership for Carbon Accounting Financials",
    "Fossil fuel companies exclusion",
    "ESG funds",
    "Green bond issues",
    "ESG investing in Asia",
    "Clean energy investment",
    "ESG disclosures by public companies",
    "Integrated Report",
    "Greenhouse gases reduction",
    "TCFD reporting",
    "ESG engagement",
    "Sustainability report publication",
    "Net zero emissions target",
    "Sustainability loan",
    "Most popular stock among ESG funds",
    "Impact investment manager",
    "Plastic waste recycling",
    "Sustainability bond issuance",
    "ESG-X index",
    "Green bond issuance",
    "ESG and sustainability disclosure","climate change",
    "carbon footprint",
    "renewable energy",
    "pollution",
    "biodiversity",
    "conservation",
    "emissions",
    "sustainable practices",
    "deforestation",
    "energy efficiency"]

social_keywords = ['society', 'community', 'people', 'diversity', 'equality', 'inclusion', 'welfare', 'human rights', 'poverty', 'well-being',"corporate responsibility",
    "community",
    "social responsibility",
    "human rights",
    "diversity",
    "inclusion",
    "welfare",
    "equality",
    "social impact",
    "social criteria",
    "executive pay agreements",
    "shareholder activism",
    "dealmakers",
    "corporate social responsibility",
    "human rights",
    "sustainable development goals",
    "climate-related disclosure",
    "ESG criteria",
    "net zero",
    "sustainable strategies",
    "net zero carbon emissions",
    "climate risk",
    "carbon emissions",
    "carbon reduction",
    "sustainability goals",
    "climate transition",
    "climate initiatives",
    "climate risk",
    "climate strategy",
    "climate finance",
    "sustainable solutions",
    "sustainable investing",
    "sustainable infrastructure",
    "sustainable development",
    "sustainable economy","diversity",
    "human rights",
    "labor practices",
    "employee welfare",
    "community engagement",
    "social justice",
    "health and safety",
    "consumer protection",
    "philanthropy",
    "stakeholder relations"]

governance_keywords = ['governance', 'regulation', 'policy', 'law', 'compliance', 'ethics', 'transparency', 'accountability', 'audit', 'corporate governance',"sustainability report",
    "corporate sustainability reporting",
    "corporate governance",
    "stewardship",
    "TCFD",
    "stewardship code",
    "climate disclosure rules",
    "disclosure rules",
    "sustainability disclosure",
    "ESG disclosure",
    "regulatory regime",
    "financial services",
    "ESG disclosure rules",
    "regulatory framework",
    "climate-related disclosure",
    "executive pay agreements",
    "corporate governance",
    "board of directors",
    "transparency",
    "ethics",
    "executive compensation",
    "shareholder rights",
    "regulatory compliance",
    "risk management",
    "accountability",
    "anti-corruption"]